### ISSUE TITLE
Error: '/opt/hostedtoolcache/node/15.8.0/x64/bin/npx'

### ISSUE THREAD

**Issue by charklewis** [raulanatol/jest-coverage-comment-action#7]
I am trying to use the action, however it keeps failing with the error:

```
Run raulanatol/jest-coverage-comment-action@v1.0.6
  with:
    github-token: ***
    jest-command: npx jest --coverage
    only-changes: true
    delete-previous: true

Error: ExecCommand error: Error: The process '/opt/hostedtoolcache/node/12.20.1/x64/bin/npx' failed with exit code 1
Error: The process '/opt/hostedtoolcache/node/12.20.1/x64/bin/npx' failed with exit code 1
```

I thought this might be due to the node version but it also fails on versions up to Node 15.x.  Are you able to advise where I am going wrong?

```
unit_tests_latest:
    name: Unit Tests - Latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Restore cached dependencies
        uses: actions/cache@v2
        with:
          key: node-modules-${{ hashFiles('yarn.lock') }}
          path: |
            ~/.cache/yarn
            **/node_modules
      - name: Install dependencies
        run: yarn install --immutable
      - name: Test using Jest
        run: yarn run test:ci
        env:
          CI: true
      - name: Add Jest coverage to PR
        uses: raulanatol/jest-coverage-comment-action@v1.0.6
        id: jest_coverage
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```
